# config/sidekiq.yml

:concurrency: 5
:queues:
  - default
  - mailers
:timeout: 30
:logfile: ./log/sidekiq.log
:pidfile: ./tmp/pids/sidekiq.pid

# Optional: environment-specific settings
:development:
  :concurrency: 2
  :queues:
    - default
    - mailers

:production:
  :concurrency: 10
  :queues:
    - [critical, 3]
    - [default, 2]
    - [mailers, 1]
